name: Test 🧪

on:
  workflow_call:
    inputs:
      godot-version:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: ${{ inputs.godot-version }}
          include-templates: false
          use-dotnet: false

      - name: Run GUT tests
        run: |
          make import
          make test
